#!/bin/bash
command_args=()
host=""
zone=""
ssh_args=()
while test $# -gt 0; do
    case "$1" in
        *:ZONE_DELIMITER:*)
            host=$(echo $1 | sed 's/:ZONE_DELIMITER:.*//')
            zone=$(echo $1 | sed 's/.*:ZONE_DELIMITER://')
            shift
            while test $# -gt 0; do
                if [ ${#command_args[@]} -eq 0 ]; then
                    command_args+=(--command)
                    command_args+=("")
                fi
                command_args[1]="${command_args[1]} $1"
                shift
            done
            break
        ;;
    esac
    if [ ${#ssh_args[@]} -eq 0 ]; then
        ssh_args+=(--)
    fi
    ssh_args+=($1)
    shift
done
gcloud compute ssh "$host" "${command_args[@]}" --quiet --zone "$zone" "${ssh_args[@]}"
