#!/bin/sh

command=""
host=""
zone=""
ssh_args=""
while test $# -gt 0; do
    case "$1" in 
        *:ZONE_DELIMITER:*)
            host=$(echo $1 | sed 's/:ZONE_DELIMITER:.*//')
            zone=$(echo $1 | sed 's/.*:ZONE_DELIMITER://')
            shift
            while test $# -gt 0; do
                if [$command -eq ""]; then
                    command="--command=\""
                fi
                command="$command $1"
                shift
            done
            command="$command\""
        ;;
    esac

    if [$ssh_args -eq ""]; then
        ssh_args="--"
    fi
    ssh_args="$ssh_args  $1"
    shift
done

gcloudCommand="/etc/google-cloud-sdk/bin/gcloud compute ssh $host $command --zone=$zone $ssh_args"
$gcloudCommand
